pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/AbelBusi/SOFTWARE-CONSULTORIO-MEDICO.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('consultorio') {
                    bat 'mvn clean verify'
                }
            }
            post {
                always {
                    junit 'consultorio/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                dir('consultorio') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('Archivar JAR') {
            steps {
                archiveArtifacts artifacts: 'consultorio/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Build exitoso'
        }
        failure {
            echo 'Build falló'
        }
        unstable {
            echo 'Tests fallaron (build inestable)'
        }
    }
}