spring.application.name=consultorio

# Puerto
server.port=8088

# MariaDB
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/consultoriomedico

spring.datasource.username=admin_local
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger
springdoc.swagger-ui.operationsSorter=method

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Recursos estáticos
spring.mvc.static-path-pattern=/**

# Multipart
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

·Seguridad
aplication.security.jwt.secret=2f2f5820a465f2b8cba79206777ef612690735acdb4fd877d6ef4f7411f32fe8a61c4fff2fe8eb654d67a4a3937a2100707c6dcf3f4a4927af05d87d98043ac6
aplication.security.jwt.expiration=28800000
aplication.security.jwt.refresh.expiration=28800000